Catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name = 'books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name = 'book-detail'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name = 'author-detail'),
]

TheLocalLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('Catalog.urls')),
    path('', RedirectView.as_view(url = 'catalog/')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Catalog/models.py
from django.db import models
from django.urls import reverse
import uuid # Required for unique book instances

# Create your models here.

class Genre(models.Model):
    '''Model representing a book genre.'''
    name = models.CharField(max_length = 200, help_text = 'Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        '''String for representing the Model object.'''
        return self.name

class Book(models.Model):
    '''Model representing a book (but not a specific copy of a book).'''
    title = models.CharField(max_length = 200)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, null = True)
    summary = models.TextField(max_length = 1000, help_text = 'Enter a breif description of the book')
    isbn = models.CharField('ISBN', max_length = 13, unique = True, help_text = '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN Number</a>')
    genre = models.ManyToManyField(Genre, help_text = 'Select a genre for this book')
    language = models.ForeignKey('Language', on_delete = models.SET_NULL, null = True   )

    def __str__(self):
        '''String for representing the Model object.'''
        return self.title
    
    def get_absolute_url(self):
        '''Returns the url to access a detail record for this book.'''
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        '''Create a string for the Genre. This is required to display genre in Admin.'''
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    '''Model representing a specific copy of a book (i.e. that can be borrowed from the library).'''
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = 'Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete = models.RESTRICT, null = True)
    imprint = models.CharField(max_length = 200)
    due_back = models.DateField(null = True, blank = True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length = 1,
        choices = LOAN_STATUS,
        blank = True,
        default = 'm',
        help_text = 'Book availability'
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        '''String for representing the Model object.'''
        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    '''Model representing an author.'''
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null = True, blank = True)
    date_of_death = models.DateField('Died', null = True, blank = True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        '''Returns the url to access a particular author instance.'''
        return reverse('author-detail', args = [str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    '''Model representing a Language (e.g. English, Hindi, French, etc.).'''
    name = models.CharField(max_length = 200, help_text = "Enter the book's natural language (e.g. English, Hindi, French, etc.)")

    def __str__(self):
        '''String for representing the Model object.'''
        return self.name

Catalog/views.py
from django.shortcuts import render
from .models import Author, Book, BookInstance, Genre
from django.views import generic

def index(request):
    '''View function for home page of site.'''

    num_authors = Author.objects.all().count()
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_authors': num_authors,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context = context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

Catalog/templates/Catalog/author_detail.html
{% extends 'base_generic.html' %}

{% block title %}
    Author Detail - {{ author.first_name }} {{ author.last_name }} | The Local Library
{% endblock %}

{% block content %}
    <h1>Author: {{author.last_name}}, {{author.first_name}}</h1>
    
    <p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Books</h4>
        
        {% if author.book_set.all %}
            <dl>
                {% for book in author.book_set.all %}
                    <dt><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.bookinstance_set.all.count }})</dt>
                    <dd>{{ book.summary }}</dd>
                {% endfor %}
            </dl>
        {% else %}
            <p>No books by this author present in the library.</p>
        {% endif %}
    </div>
{% endblock %}

Catalog/templates/Catalog/author_list.html
{% extends 'base_generic.html' %}

{% block title %}
    Author List | The Local Library
{% endblock %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li><a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a> ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

Catalog/templates/Catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block title %}
    Book Detail - {{ book.title }} | The Local Library
{% endblock %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:', ' }}</p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

Catalog/templates/Catalog/book_list.html
{% extends 'base_generic.html' %}

{% block title %}
    Book List | The Local Library
{% endblock %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
            <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

Catalog/templates/base_generic.html
<!DOCTYPE html>

<html lang="en">

    <head>

        <title>{% block title %}The Local library{% endblock %}</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>

    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li><a href="{% url 'books' %}">All Books</a></li>
                            <li><a href="{% url 'authors' %}">All Authors</a></li>
                        </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </body>

</html>

Catalog/templates/index.html
{% extends 'base_generic.html' %}

{% block title %}
    Home | The Local Library
{% endblock %}

{% block content %}
    <h1>The Local Library Home</h1>

    <p>Welcome to TheLocalLibrary, my <em>first website</em> designed with <strong>Django!</strong></p>

    <h2>Dynamic Content</h2>

    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
    </ul>

    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}